# Generated by Django 3.1 on 2020-08-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(choices=[('IX', 'Iphone X'), ('IXR', 'Iphone XR'), ('IXS', 'Iphone XS'), ('IXSM', 'Iphone XS MAX'), ('I11', 'Iphone 11'), ('I11P', 'Iphone 11 Pro'), ('I11PM', 'Iphone 11 Pro MAX'), ('M', 'Macbook'), ('MA', 'Macbook Air'), ('MP', 'Macbook Pro'), ('A1', 'Airpod 1세대 '), ('A2', 'Airpod 2세대'), ('AP', 'Airpod Pro')], max_length=30)),
                ('price', models.IntegerField()),
                ('Issold', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('region', models.CharField(choices=[('SE', '서울'), ('GY', '경기'), ('BU', '부산'), ('IN', '인천'), ('GW', '광주')], max_length=10)),
            ],
        ),
    ]
