# Generated by Django 3.1 on 2020-08-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='item',
            name='longitude',
        ),
        migrations.AddField(
            model_name='item',
            name='body',
            field=models.TextField(blank=True, default='Nothing written from user', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='userfile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='Issold',
            field=models.IntegerField(default=0),
        ),
    ]
