# Generated by Django 3.1 on 2020-08-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0002_auto_20200831_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
