# Generated by Django 3.1 on 2020-09-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0005_auto_20200831_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='region',
            field=models.CharField(choices=[('SE', 'Seoul'), ('GY', 'Gyeonggi'), ('BU', 'Busan'), ('IN', 'Incheon'), ('GW', 'Gwangju')], max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='what',
            field=models.CharField(choices=[('IX', 'Iphone X'), ('IXR', 'Iphone XR'), ('IXS', 'Iphone XS'), ('IXSM', 'Iphone XS MAX'), ('I11', 'Iphone 11'), ('I11P', 'Iphone 11 Pro'), ('I11PM', 'Iphone 11 Pro MAX'), ('M', 'Macbook'), ('MA', 'Macbook Air'), ('MP', 'Macbook Pro'), ('A1', 'Airpod 1st Gen '), ('A2', 'Airpod 2nd Gen'), ('AP', 'Airpod Pro')], max_length=30),
        ),
    ]
