# Generated by Django 3.1 on 2020-09-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0006_auto_20200901_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='userfile',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
