# Generated by Django 3.1 on 2020-09-07 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0007_auto_20200901_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='item',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
