# Generated by Django 3.1 on 2020-09-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0017_auto_20200914_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
